[package]
name = "socket-garden-darwin-firewall"
version = "0.1.0"
authors = ["Leigh Brenecki <l@leigh.net.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.26.0"
